### ISSUE TITLE
error with load assistant on jeedom side

### ISSUE THREAD

**Issue by rudloffl** [snipsco/Snips-Jeedom-Plugin-Issues#1]
Hello,
I'm having trouble to load the assistant on the jeedom side.
# What I did so far:
* updated snips (apt-get update and npm...)
* installed the jeedomOfficial skill
* sam watch shows that the skill is correct (just complaining about pips version...)
* Installed the snips plugin on jeedom
* Set the ip (192.168.1.28, the same i use for SSH)
* When I try to load the assistant, I fill the login/password (the one used to connect via ssh)
* Tells me the IP may not be correct :-(
* When I use "sam devices" (ssh console on the pi with snips), only the IP jeedom shows (it's a R3)

# My set-up:
* jeedom 3.2.1 on a raspberry pi 3
* Snips (updated) on a raspberry pi 3

Any solution or help ?

**Comment by CoorFun** [comment]
Hello, 

This is a bug. 

People who have this issues, please reinstall your snips plugin.

You should at least have the version : 2018-07-25 18:42:36.
