### ISSUE TITLE
TTS French

### ISSUE THREAD

**Issue by Ultchad** [snipsco/Snips-Jeedom-Plugin-Issues#12]
I have a little problem with my french install of snips (or it's a bad config of me)
When i click on snips device for test the TTS he speak with english accent

I check the mqtt brocker and i find in json 
```json
{
  "text": "Dispositif default est ici!",
  "siteId": "default",
  "lang": "fr_FR"
}
```

When i use othe snips app (with de good accent) "lang" parm is "fr"

It's only with jeedom app

**Comment by CoorFun** [comment]
Hello,

Thanks for reporting. This bug has been fixed. The release is now on the beta version, will be merged to stable branch within this week! : )
