### ISSUE TITLE
"OR" in condition?

### ISSUE THREAD

**Issue by fwehrle** [snipsco/Snips-Jeedom-Plugin-Issues#4]
Hi,
An improvment idea : is it possible to ad "OR" condition in bindings? or better : a free field to evaluate conditions, like in jeedom scenarios?

**Comment by CoorFun** [comment]
In today's release [Version: 2018-08-01 16:35:54], we supported synonyms, which means you can set only if condition equals to not only 'salon', 'chambre' but also 'salon, chambre, bureau" etc.. Use `,` to separate different word (synonyms) this can be considered as a or condition as well. 

Not sure if this can be your case?

**Comment by fwehrle** [comment]
Oh nice! (I didn't see this evolution in the changelog) : that's perfect.
My "nice to have" proposal is a little much more complicated (use formula and jeedom objects like in scenarios. ex. : "#house_room# matches /"chambre/" ET #[Sécurité][Franck][Présence]# == 1 ).. 
But This one is already very usefull.
