### ISSUE TITLE
Binding Duplication missing field

### ISSUE THREAD

**Issue by fwehrle** [snipsco/Snips-Jeedom-Plugin-Issues#5]
Hi,

When you duplicate a binding, the "ONLY_IF" element is not duplicated and stay empty.

**Comment by fwehrle** [comment]
Hi Coorfang,
I just see that's the same problem when I add a "scenario" action in bindings : the scenario is empty when I duplicate.

**Comment by CoorFun** [comment]
Hi @fwehrle , this is the issue of Jquery clone function, we have already fixed it.
