### ISSUE TITLE
issue : Default feedback

### ISSUE THREAD

**Issue by oguh22** [snipsco/Snips-Jeedom-Plugin-Issues#7]
Hello,

On my assistant I have some apps like Weather, or Time that are not linked to Jeedom  but because Jeedom plugin catch all intents from assistant, if I ask for the weather, I get the correct answer but just after, the default feedback "sorry I didn't undertand" is play from Jeedom

**Comment by oguh22** [comment]
Just see that we can disable an intent on jedom plugin but I didn't test it
And also need to check if it is keep in configuration Export/import

**Comment by CoorFun** [comment]
Hi @oguh22 , this has been achieved. Now only "xxxxJeedom" intent will be loaded to jeedom plugin. Be sure you have this "jeedom" (Not case sensitive) as part of intent name.
